# Main `RunSpec`s for the benchmarking.

entries: [
  ##### ViLLM #####

  ## Question Answering  #####
  {description: "villm_question_answering:dataset=mlqa,model=code", priority=1, groups: ["question_answering"]}
  {description: "villm_question_answering:dataset=xquad_xtreme,model=code", priority=1, groups: ["question_answering"]}

  ## Summarization  #####
  {description: "villm_summarization:dataset=vietnews,temperature=1,model=text", priority=1, groups: ["summarization"]}
  {description: "villm_summarization:dataset=wiki_lingua,temperature=1,model=text", priority=1, groups: ["summarization"]}

]